# Generated by Django 4.2.16 on 2026-05-15 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主播ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('platform', models.CharField(max_length=16, verbose_name='平台')),
                ('fans', models.BigIntegerField(default=0, verbose_name='粉丝数')),
                ('avg_gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='平均GMV')),
                ('return_rate', models.FloatField(default=0.0, verbose_name='退货率')),
                ('avatar_seed', models.CharField(default='seed', max_length=16, verbose_name='头像种子')),
            ],
            options={
                'verbose_name': '主播',
                'verbose_name_plural': '主播',
                'db_table': 'anchor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='品类ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='品类名称')),
                ('icon_glyph', models.CharField(default='✦', max_length=8, verbose_name='图标')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='父品类')),
            ],
            options={
                'verbose_name': '品类',
                'verbose_name_plural': '品类',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='直播ID')),
                ('title', models.CharField(max_length=255, verbose_name='直播标题')),
                ('platform', models.CharField(max_length=16, verbose_name='平台')),
                ('start_at', models.DateTimeField(verbose_name='开播时间')),
                ('duration_min', models.IntegerField(default=60, verbose_name='时长(分)')),
                ('peak_audience', models.IntegerField(default=0, verbose_name='峰值观众')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='GMV')),
                ('conversion_rate', models.FloatField(default=0.0, verbose_name='转化率')),
                ('anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='livestreams', to='core.anchor', verbose_name='主播')),
            ],
            options={
                'verbose_name': '直播间',
                'verbose_name_plural': '直播间',
                'db_table': 'live_stream',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=64, verbose_name='用户名')),
                ('pass_word', models.CharField(blank=True, default='', max_length=64, verbose_name='密码')),
                ('avatar_seed', models.CharField(default='seed', max_length=16, verbose_name='头像种子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '前台用户',
                'verbose_name_plural': '前台用户',
                'db_table': 'user_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('brand', models.CharField(blank=True, default='', max_length=64, verbose_name='品牌')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('sales', models.IntegerField(default=0, verbose_name='累计销量')),
                ('rating', models.FloatField(default=4.5, verbose_name='评分')),
                ('image_seed', models.CharField(default='seed', max_length=16, verbose_name='占位图种子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='core.category', verbose_name='品类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LiveStreamProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sold_qty', models.IntegerField(default=0, verbose_name='售出数量')),
                ('sold_gmv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='售出GMV')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_products', to='core.livestream', verbose_name='直播间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_products', to='core.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '直播间商品',
                'verbose_name_plural': '直播间商品',
                'db_table': 'live_stream_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.useraccount', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorite_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BrowseLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browse_logs', to='core.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browse_logs', to='core.useraccount', verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览日志',
                'verbose_name_plural': '浏览日志',
                'db_table': 'browse_log',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_categor_26b384_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-sales'], name='product_sales_9ac42e_idx'),
        ),
        migrations.AddIndex(
            model_name='livestreamproduct',
            index=models.Index(fields=['live'], name='live_stream_live_id_4ded76_idx'),
        ),
        migrations.AddIndex(
            model_name='livestreamproduct',
            index=models.Index(fields=['product'], name='live_stream_product_22da4c_idx'),
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['-start_at'], name='live_stream_start_a_3b7e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='livestream',
            index=models.Index(fields=['platform'], name='live_stream_platfor_ff45fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritelist',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='browselog',
            index=models.Index(fields=['user', '-viewed_at'], name='browse_log_user_id_a0fa95_idx'),
        ),
    ]
